-- liquibase formatted sql

-- changeset klikli:1
CREATE TABLE socks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color       VARCHAR(255) NOT NULL ,
    cotton_part INTEGER CHECK ( cotton_part > -1 and  cotton_part < 101) ,
    quantity    INTEGER CHECK ( quantity > 0 )
);